name: 'PackAdvice'
description: 'A GitHub actions that provides advice for improving Minecraft Java Edition resource pack'
inputs:
  token:
    description: 'The GitHub authentication token.'
    required: true
    default: ${{ github.token }}
  path:
    description: 'Relative path from the repository root to the pack directory.'
    required: true
    default: '.'
  version:
    description: 'The PackAdvice version the action will use.'
    required: true
    default: 'latest'
  comment:
    description: 'If true, enable a result comment on the commit.'
    required: true
    default: 'true'
  comment_repository:
    description: 'If commit option is true, the full name of the target repository.'
    required: true
    default: ${{ github.repository }}
  comment_sha:
    description: 'If commit option is true, the commit SHA.'
    required: false
  comment_format:
    description: 'Change the comment to any format. `{body}` will be replaced to output.'
    required: true
    default: '{body}'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'refresh-ccw'
  color: 'green'
